### PR TITLE
allow loading yaml files into a specified key

### LINKED ISSUE #96: Using a source file containing a yaml list
I am switching an existing repo to mkdocs. For historical reason, my data is stored as a list in the root of a yaml file. Currently, when a file is loaded, `update(self.variables, content)` is called. This naturally fails if `content` is a list. Since this yaml format is used in several places throughout my codebase, I would prefer to keep it as is.

Therefore I have two questions:

1. Is there a workaround in the current version of the macros plugin, which would allow to load yaml files containing lists?
2. Would it be desirable to be able to load yaml content other than dictionaries, for example by putting them in a dictionary `{filename: content}`

Thanks for the powerful plugin!

### PR DESCRIPTION
**Pull request by akhmerov**
Closes #96 

So far this is a demo of a possible solution, if this is desirable, I'll update the docs and the tests.

### CODE REVIEW

**Comment by fralau** [comment]
Sounds good. 

Please add comments to explain the new use case in the config file, and what the code does.

**Comment by akhmerov** [comment]
Should be good to go, I've edited all the places where `include_yaml` occurs in codebase.

**Comment by fralau** [comment]
Thanks for the great contribution!

**Comment by akhmerov** [comment]
Awesome! A quick question: do you have a timeline for the next release? Otherwise I can install from master, but pinning is nicer.

**Comment by fralau** [comment]
No formal timeline at the moment, but I can release a new tagged version on github in short order. 

It will take a little time before I push it to pypi, since this new function should be tested more extensively, so that we are sure that it integrates well into the current ecosystem.

**Pull request merged**
