### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by eyllanesc**
- [x] Fix `### How to add a pluglet to an mkdocs project?` section.
- [x] Fix TOC.

The following image shows that the `### How to add a pluglet to an mkdocs project?` section of the README does not render correctly due to a strange character (or perhaps another cause). Besides that section is not shown in the TOC.   

Screenshot_20220103_094209

### CODE REVIEW

**Comment by fralau** [comment]
Please provide a justification to this pull request?

**Comment by eyllanesc** [comment]
@fralau I thought the change was showing the error, I already added the justification anyway.

**Comment by fralau** [comment]
OK, I got it for the title.

What problem was there in the TOC?

**Comment by eyllanesc** [comment]
> What problem was there in the TOC?

The TOC is incomplete, you can see the section "using pluglets".

Current:

old


After:

new

**Pull request merged**
