### PR TITLE
removed site navigation argument from on_page_markdown

### PR DESCRIPTION
**Pull request by Useurmind**
mkdocs 1.0.2 does not provide this parameter anymore

### CODE REVIEW

**Comment by fralau** [comment]
Etiquette should have required that you ask for agreement before uploading a fork with the same name pypi. With that *fait accompli*, you are denying users of pypi the right of using an updated version of the genuine tool.

**Comment by Useurmind** [comment]
If you want to take over the PyPi package repository, I am happy to hand it over to you.
I did not expect that you currently want to provide a PyPi package (your setup guide uses a install script), and needed a package to proceed with our project.

Did you merge my pull request?
I don't mind you taking the package creation stuff I implemented to create your own package.

**Comment by fralau** [comment]
Thanks a lot for your offer, and it would be good if you handed the Pypi repository over to me.

No, I did not integrate your modifications, partly because I did not fully agree with them (especially on versions), and I had my own waiting to be integrated. I also have my own setup for pypi, but I had not implemented it (I just needed to execute it).

For removing the site navigation argument, I suggest you make your case with an issue, and we go on from there?

**Comment by Useurmind** [comment]
I have deleted the package from PyPi.

As you did not integrate my changes, it makes no sense to leave the versions online. You can create your own repo from here.

I did however create a package useurmind-mkdocs-macros-plugin that will serve me as a fixed version until your package is compatible with mkdocs 1.0.2.

**Comment by fralau** [comment]
Perfect, I have immediately created the repository on pypi. By all means for your own pypi fork, that’s the spirit of open source software.

I will quickly take a look on the issue about compatibility with mkdocs 1.0.2.

**Pull request closed without merging**
